/*

 SNAKE_SPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char snake_sprites[] =
{
  0x7E,0x7E,0xFF,0xFF,0xDB,0xBD,0xDB,0x99,
  0xFF,0x99,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
  0xFE,0xFE,0xFF,0xE3,0xF3,0xE7,0xFF,0xFF,
  0xFF,0xFF,0xF3,0xE7,0xFF,0xE3,0xFE,0xFE
};

/* End of SNAKE_SPRITES.C */
